# Getting All Players Active

In [1]:
import pandas as pd
import numpy as np
import glob
import os
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', 500)

In [2]:
active = pd.read_csv('../data/cleaned/sleeperPlayers.csv')

In [3]:
active.head()

,Unnamed: 0,espn_id,number,practice_participation,full_name,search_first_name,metadata,hashtag,height,fantasy_data_id,sport,injury_notes,years_exp,first_name,status,injury_body_part,weight,birth_state,search_full_name,position,depth_chart_position,sportradar_id,practice_description,depth_chart_order,search_last_name,player_id,injury_status,age,search_rank,pandascore_id,news_updated,birth_date,injury_start_date,yahoo_id,rotowire_id,last_name,college,high_school,fantasy_positions,active,rotoworld_id,stats_id,team,birth_country,birth_city,gsis_id
0,2103,17054.0,60.0,NaN,Cody Booth,cody,NaN,#CodyBooth-NFL-FA-60,"6'5""",16426.0,nfl,NaN,1.0,Cody,Inactive,NaN,285.0,NaN,codybooth,OT,NaN,4cd4976e-e230-4935-ad3f-c12876a41350,NaN,NaN,booth,2103,NaN,27.0,9999999.0,NaN,NaN,1991-04-22,NaN,27841.0,9866.0,Booth,Temple,NaN,['OL'],False,NaN,NaN,NaN,NaN,NaN,NaN
1,6250,3916426.0,0.0,NaN,Eurndraus Bryant,eurndraus,NaN,#EurndrausBryant-NFL-FA-0,NaN,21183.0,nfl,NaN,0.0,Eurndraus,Inactive,NaN,NaN,NaN,eurndrausbryant,DT,NaN,9ff46edb-988f-4c8a-ad56-0502808ca1a6,NaN,NaN,bryant,6250,NaN,NaN,9999999.0,NaN,NaN,NaN,NaN,32538.0,NaN,Bryant,NaN,NaN,['DL'],True,NaN,NaN,NaN,NaN,NaN,NaN
2,4116,2972820.0,71.0,NaN,Antonio Garcia,antonio,NaN,#AntonioGarcia-NFL-FA-71,"6'6""",18962.0,nfl,NaN,3.0,Antonio,Inactive,NaN,293.0,NaN,antoniogarcia,OT,NaN,a2b6e1f9-1f06-45e3-b6e9-79ec8490e5ef,NaN,NaN,garcia,4116,NaN,26.0,9999999.0,NaN,1.560222e+12,1993-12-10,NaN,30198.0,11794.0,Garcia,Troy,NaN,['OL'],True,12247.0,NaN,NaN,NaN,NaN,00-0033922
3,6177,3121634.0,99.0,NaN,Khalen Saunders,khalen,NaN,#KhalenSaunders-NFL-KC-99,"6'0""",20934.0,nfl,NaN,2.0,Khalen,Active,NaN,324.0,NaN,khalensaunders,DT,RDT,757c55e1-2f3a-41d2-a211-16bf577a1586,NaN,2.0,saunders,6177,NaN,25.0,1596.0,NaN,1.603596e+12,1996-08-09,NaN,31916.0,13746.0,Saunders,Western Illinois,Parkway Central (MO),['DL'],True,NaN,NaN,KC,NaN,NaN,00-0035656
4,5870,3917792.0,8.0,NaN,Daniel Jones,daniel,NaN,#DanielJones-NFL-NYG-8,"6'5""",20841.0,nfl,NaN,2.0,Daniel,Active,NaN,220.0,NaN,danieljones,QB,QB,0042266b-cb28-4012-bfd2-06650badad97,NaN,1.0,jones,5870,NaN,24.0,113.0,NaN,1.628274e+12,1997-05-27,NaN,31838.0,13491.0,Jones,Duke,Charlotte Latin (NC),['QB'],True,13963.0,879981.0,NYG,NaN,NaN,00-0035710

In [4]:
# active['player'] = active['Player'].apply(lambda x: x.split("\\")[0])

In [5]:
# active['position'] = active['Pos']

In [6]:
# active['team'] = active['Tm']

In [7]:
active.head()

,Unnamed: 0,espn_id,number,practice_participation,full_name,search_first_name,metadata,hashtag,height,fantasy_data_id,sport,injury_notes,years_exp,first_name,status,injury_body_part,weight,birth_state,search_full_name,position,depth_chart_position,sportradar_id,practice_description,depth_chart_order,search_last_name,player_id,injury_status,age,search_rank,pandascore_id,news_updated,birth_date,injury_start_date,yahoo_id,rotowire_id,last_name,college,high_school,fantasy_positions,active,rotoworld_id,stats_id,team,birth_country,birth_city,gsis_id
0,2103,17054.0,60.0,NaN,Cody Booth,cody,NaN,#CodyBooth-NFL-FA-60,"6'5""",16426.0,nfl,NaN,1.0,Cody,Inactive,NaN,285.0,NaN,codybooth,OT,NaN,4cd4976e-e230-4935-ad3f-c12876a41350,NaN,NaN,booth,2103,NaN,27.0,9999999.0,NaN,NaN,1991-04-22,NaN,27841.0,9866.0,Booth,Temple,NaN,['OL'],False,NaN,NaN,NaN,NaN,NaN,NaN
1,6250,3916426.0,0.0,NaN,Eurndraus Bryant,eurndraus,NaN,#EurndrausBryant-NFL-FA-0,NaN,21183.0,nfl,NaN,0.0,Eurndraus,Inactive,NaN,NaN,NaN,eurndrausbryant,DT,NaN,9ff46edb-988f-4c8a-ad56-0502808ca1a6,NaN,NaN,bryant,6250,NaN,NaN,9999999.0,NaN,NaN,NaN,NaN,32538.0,NaN,Bryant,NaN,NaN,['DL'],True,NaN,NaN,NaN,NaN,NaN,NaN
2,4116,2972820.0,71.0,NaN,Antonio Garcia,antonio,NaN,#AntonioGarcia-NFL-FA-71,"6'6""",18962.0,nfl,NaN,3.0,Antonio,Inactive,NaN,293.0,NaN,antoniogarcia,OT,NaN,a2b6e1f9-1f06-45e3-b6e9-79ec8490e5ef,NaN,NaN,garcia,4116,NaN,26.0,9999999.0,NaN,1.560222e+12,1993-12-10,NaN,30198.0,11794.0,Garcia,Troy,NaN,['OL'],True,12247.0,NaN,NaN,NaN,NaN,00-0033922
3,6177,3121634.0,99.0,NaN,Khalen Saunders,khalen,NaN,#KhalenSaunders-NFL-KC-99,"6'0""",20934.0,nfl,NaN,2.0,Khalen,Active,NaN,324.0,NaN,khalensaunders,DT,RDT,757c55e1-2f3a-41d2-a211-16bf577a1586,NaN,2.0,saunders,6177,NaN,25.0,1596.0,NaN,1.603596e+12,1996-08-09,NaN,31916.0,13746.0,Saunders,Western Illinois,Parkway Central (MO),['DL'],True,NaN,NaN,KC,NaN,NaN,00-0035656
4,5870,3917792.0,8.0,NaN,Daniel Jones,daniel,NaN,#DanielJones-NFL-NYG-8,"6'5""",20841.0,nfl,NaN,2.0,Daniel,Active,NaN,220.0,NaN,danieljones,QB,QB,0042266b-cb28-4012-bfd2-06650badad97,NaN,1.0,jones,5870,NaN,24.0,113.0,NaN,1.628274e+12,1997-05-27,NaN,31838.0,13491.0,Jones,Duke,Charlotte Latin (NC),['QB'],True,13963.0,879981.0,NYG,NaN,NaN,00-0035710

In [8]:
active['player'] = active['full_name']

In [9]:
# active['player_id'] = active['index']

In [10]:
keepcols = ['player_id', 'player', 'position', 'team']
activesmall = active[keepcols]

In [11]:
activesmall.columns

Index(['player_id', 'player', 'position', 'team'], dtype='object')

In [17]:
offensepos = ['WR','RB','TE','QB','K','DEF']

In [18]:
activeoffense = activesmall[activesmall['position'].isin(offensepos)]

In [19]:
len(activeoffense)

2796

In [21]:
activeoffense.to_csv('../data/cleaned/allPlayers2021.csv')